### ISSUE TITLE
Not starting anymore with Python 3.11

### ISSUE THREAD

**Issue by mlatorre31** [m3047/trualias#10]
tcp_virtual_server.py do not to start anymore on Python 3.11 with following error:

> DEBUG:asyncio:Using selector: EpollSelector
Traceback (most recent call last):
File "/tmp/docker-mailserver/trualias/python/tcp_virtual_server.py", line 108, in <module>
base_server.main(allocate_context, base_server.resolve_config_files(CONFIG_FILE), config_loader)
File "/tmp/docker-mailserver/trualias/python/tcp_table_server.py", line 353, in main
server = loop.run_until_complete(coro)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/asyncio/base_events.py", line 653, in run_until_complete
return future.result()
^^^^^^^^^^^^^^^
File "/usr/lib/python3.11/asyncio/streams.py", line 85, in start_server
return await loop.create_server(factory, host, port, **kwds)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: BaseEventLoop.create_server() got an unexpected keyword argument 'loop'

Look like the loop argument is the culprit.
https://github.com/m3047/trualias/blob/215ff9aea0fa5b9458d6f6ba4a0988e71e7b372a/python/tcp_table_server.py#L340

Removing it allows to start again and working, however I am not a asyncio guru to find out if this brings more troubles or is enough...
Running Python 3.11.2

Btw, great program! Thank you very much.

**Comment by m3047** [comment]
Hi, thanks for including the line reference and the traceback. The gist of it is I think you're not on a version which has support for 3.11, and you should update your Docker container. (I'd love to know: is this a homegrown container or is it somebody's distribution?)

Analysis, bordering on pedantry, follows...

That, as well as the line where the traceback occurs (line 341), are in the `def run_36(...)` runpath rather than the `def run_311(...)` path. You can infer from that that there are some differences in runcode depending on the python version.

BUT the line number for the code (`server = loop.run_until_complete(coro)`) in the traceback is 353! I went back and found that code, at that line number, at 09414637d0a167e01d031db86ce902c3d6485eab: 

https://github.com/m3047/trualias/blob/09414637d0a167e01d031db86ce902c3d6485eab/python/tcp_table_server.py#L353

As you can see there is no differentiation between python versions at that point.

If this was commercial support I'd probably stop here, but on the offchance you're part of the support / ops brotherhood / sisterhood my initial thought was "why the devil isn't it detecting 3.11?" Going down that path, I would have asked for the output of `sysconfig.get_python_version()`. However...

In the current version (215ff9aea0fa5b9458d6f6ba4a0988e71e7b372a) there is an undocumented config parameter `PYTHON_IS_311` which is a boolean (`true`,`false` or `1`,`0`). You shouldn't need to set this, it's really for testing. It is defaulted with this code:

https://github.com/m3047/trualias/blob/215ff9aea0fa5b9458d6f6ba4a0988e71e7b372a/python/trualias/config_base.py#L22

It is used here to determine which runpath to use:

https://github.com/m3047/trualias/blob/215ff9aea0fa5b9458d6f6ba4a0988e71e7b372a/python/tcp_table_server.py#L420

If this illuminates your path forward feel free to close the ticket. And thanks for the kind words, I find it useful too!

Regards...

**Comment by m3047** [comment]
I pinned issue #6 since that is what triggered the need for supporting version 3.11.

**Comment by mlatorre31** [comment]
Thank you for the extensive answer and sorry for missing the most obvious troubleshot step... 
I updated to the latest version and everything is working 😳

I am using [docker-mailserver/docker-mailserver](https://github.com/docker-mailserver/docker-mailserver) and leveraging their custom script to setup 

Merci!
